# Generated by Django 4.2.1 on 2023-06-06 15:21

import apps.announcement.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("text", models.TextField(null=True)),
                ("price", models.CharField(max_length=255, null=True)),
                ("status", models.CharField(max_length=50, null=True)),
                ("note", models.TextField(null=True)),
                ("is_published", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "processing_status",
                    models.CharField(
                        choices=[("P", "Pending"), ("R", "Processing"), ("D", "Done")], default="P", max_length=1
                    ),
                ),
                ("publication_date", models.DateTimeField(null=True)),
                ("modified_count", models.IntegerField(default=0)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-publication_date"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Media",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("media_type", models.CharField(choices=[("PHOTO", "Photo"), ("VIDEO", "Video")], max_length=20)),
                ("file", models.FileField(upload_to=apps.announcement.models.UniquePathAndRename())),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "announcement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="announcement.announcement",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="announcement",
            name="tags",
            field=models.ManyToManyField(related_name="announcements", to="announcement.tag"),
        ),
    ]
