# Generated by Django 4.2.1 on 2023-08-12 12:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("announcement", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="unpublished_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
