# Generated by Django 4.2.1 on 2023-06-06 15:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("announcement", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="published_message_link",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
