# Generated by Django 4.2.1 on 2023-06-18 17:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("announcement", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="media",
            options={"ordering": ["order"]},
        ),
        migrations.AddField(
            model_name="media",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
