# Generated by Django 4.2.1 on 2023-05-25 17:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("announcement", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="announcement",
            old_name="description",
            new_name="text",
        ),
    ]
