# Generated by Django 4.2.1 on 2023-05-26 00:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("announcement", "0002_rename_description_announcement_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
