# Generated by Django 4.2.1 on 2023-07-11 14:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("announcement", "0002_alter_media_options_media_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="channel_id",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="tag",
            name="type",
            field=models.CharField(
                choices=[("visible", "Visible"), ("hidden", "Hidden")], default="visible", max_length=20
            ),
        ),
    ]
