# Generated by Django 4.2.1 on 2023-08-12 13:05

from django.db import migrations
from django.db import models


def migrate_status(apps, schema_editor):
    Announcement = apps.get_model("announcement", "Announcement")

    to_update = []

    for announcement in Announcement.objects.all():
        if announcement.is_published and announcement.is_active:
            announcement.processing_status = "PUBLISHED"
            to_update.append(announcement)
        elif (not announcement.is_published) and (not announcement.is_active):
            announcement.processing_status = "INACTIVE"
            to_update.append(announcement)
        elif announcement.is_active and (not announcement.is_published):
            announcement.processing_status = "AWAITING"
            to_update.append(announcement)

    Announcement.objects.bulk_update(to_update, ["processing_status"])


class Migration(migrations.Migration):
    dependencies = [
        ("announcement", "0002_announcement_unpublished_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcement",
            name="processing_status",
            field=models.CharField(
                choices=[
                    ("AWAITING", "Awaiting Publication"),
                    ("PUBLISHED", "Published"),
                    ("UNPUBLISHED", "Unpublished"),
                    ("INACTIVE", "Inactive"),
                    ("PROCESSING", "Processing"),
                ],
                default="AWAITING",
                max_length=20,
            ),
        ),  
        migrations.RunPython(migrate_status),
        migrations.RemoveField(
            model_name="announcement",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="announcement",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="announcement",
            name="modified_at",
        ),
        migrations.RemoveField(
            model_name="announcement",
            name="modified_count",
        ),
    ]
