# Generated by Django 4.2.1 on 2023-07-12 15:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("announcement", "0003_tag_channel_id_tag_type"),
    ]

    database_operations = [migrations.AlterModelTable("Tag", "tag_tag")]

    state_operations = [migrations.DeleteModel("Tag")]

    operations = [
        migrations.SeparateDatabaseAndState(database_operations=database_operations, state_operations=state_operations)
    ]
