# Generated by Django 4.2.1 on 2023-06-15 11:49

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publishedmessage",
            name="channel_id",
            field=models.CharField(default="-1001910076143", max_length=255),
        ),
    ]
