# Generated by Django 4.2.1 on 2023-06-18 17:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0002_alter_publishedmessage_channel_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publishedmessage",
            name="channel_id",
            field=models.CharField(default="-1001921857788", max_length=255),
        ),
    ]
