version: '3.9'

services:
  db:
    image: mysql:8.1.0
    command: --default-authentication-plugin=caching_sha2_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    env_file:
      - ./.env
    volumes:
      - dbdata:/var/lib/mysql

  web:
    build: .
    working_dir: /code/web
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000 --workers 3
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis
      - migrator
    env_file:
      - ./.env

  migrator:
    build: .
    working_dir: /code/web
    command: python3 manage.py migrate
    volumes:
      - .:/code
    depends_on:
      - db

  nginx:
    image: nginx:1.25.1-alpine
    volumes:
      - ./web/static/:/code/web/static
      - ./web/media/:/code/web/media
      - ./CarWebBot.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - web
    env_file:
      - ./.env

  redis:
    image: redis:7.0
    ports:
      - 6378:6379
    env_file:
      - ./.env

  celery:
    build: .
    working_dir: /code/web
    command: celery -A core worker --beat -l info
    volumes:
      - .:/code
    depends_on:
      - web
      - db
      - redis
    env_file:
      - ./.env

volumes:
  dbdata:
