version: '3.9'

services:
  db:
    image: mysql:8.1.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
    env_file:
      - ./.env
    volumes:
      - dbdata:/var/lib/mysql

  web:
    build: .
    command: gunicorn web.core.wsgi:application --bind 0.0.0.0:8000 --workers 3
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis
    env_file:
      - ./.env

  nginx:
    image: nginx:1.25.1-alpine
    volumes:
      - ./CarWebBot.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - web
    env_file:
      - ./.env

  redis:
    image: redis:7.0
    ports:
      - 6378:6379
    env_file:
      - ./.env

  celery:
    build: .
    working_dir: /code/web
    command: celery -A web/core worker -l info
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
    env_file:
      - ./.env

  beat:
    build: .
    working_dir: /code/web
    command: celery -A web/core beat -l info
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
    env_file:
      - ./.env

volumes:
  dbdata:
